# Author: Abdul Basith

version: "3"
services:
  rabbit:
    image: rabbitmq:3.8-management
    container_name: rabbit1
    hostname: rabbit1
    restart: on-failure
    network_mode: host
    environment:
      - RABBITMQ_DEFAULT_VHOST=vhost
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_ERLANG_COOKIE=samecookie
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data:
    driver: local
